### ISSUE TITLE
No error message when report generation fails

### ISSUE THREAD

**Issue by naveen-hitachi** [JamalZeynalov/swagger-coverage-py#28]
I tried running the swagger-coverage reporter from Jenkins pipeline and due to some permission issues, the report is not generated. There is no message on the console indicating an error. It would be useful to add a check if the report generation completed and if not, provide some kind of error message.

I had to fiddle around in the agent, build this command and execute it manually.
```
.venv/lib/python3.11/site-packages/swagger_coverage_py/swagger-coverage-commandline/bin/swagger-coverage-commandline -s swagger-doc-api.json -i swagger-coverage-output/api.com/swagger-coverage.json -c swagger-coverage-config-api.json
```

to view the error message:
```
Exception in thread "main" com.github.viclovsky.swagger.coverage.SwaggerCoverageWriteException: Could not write results
        at com.github.viclovsky.swagger.coverage.core.writer.HtmlReportResultsWriter.write(HtmlReportResultsWriter.java:61)
        at com.github.viclovsky.swagger.coverage.core.generator.Generator.lambda$run$2(Generator.java:59)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at com.github.viclovsky.swagger.coverage.core.generator.Generator.run(Generator.java:59)
        at com.github.viclovsky.swagger.coverage.CommandLine.run(CommandLine.java:77)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at com.github.viclovsky.swagger.coverage.CommandLine.main(CommandLine.java:34)
Caused by: java.nio.file.AccessDeniedException: API-coverage-report.html
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
        at java.base/java.nio.file.Files.write(Files.java:3425)
        at com.github.viclovsky.swagger.coverage.core.writer.HtmlReportResultsWriter.write(HtmlReportResultsWriter.java:59)
        ... 6 more```

**Comment by naveen-hitachi** [comment]
I now see the console log can be viewed by setting DEBUG_MODE = "true"
